name: Build Android APK

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install Buildozer
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-8-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
        pip install buildozer cython
        
    - name: Setup Android SDK
      run: |
        sudo apt install -y wget
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip
        unzip commandlinetools-linux-7302050_latest.zip
        mkdir -p ~/Android/Sdk/cmdline-tools
        mv cmdline-tools ~/Android/Sdk/cmdline-tools/latest
        export PATH=$PATH:~/Android/Sdk/cmdline-tools/latest/bin
        export ANDROID_SDK_ROOT=~/Android/Sdk
        yes | sdkmanager --licenses
        sdkmanager "platforms;android-30" "build-tools;30.0.3"
        
    - name: Build APK
      run: |
        export PATH=$PATH:~/Android/Sdk/cmdline-tools/latest/bin
        export ANDROID_SDK_ROOT=~/Android/Sdk
        buildozer android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: android-apk
        path: bin/*.apk
        
    - name: Create Release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        mkdir -p release
        cp bin/*.apk release/
        cp main.py release/
        cp buildozer.spec release/
        cp requirements.txt release/
        
        # Create README
        cat > release/README.md << 'EOF'
        # 巡检自动化系统 - Android应用
        
        ## 应用信息
        - **应用名称**: SYSTEM
        - **构建时间**: $(date '+%Y-%m-%d %H:%M:%S')
        - **Git提交**: ${{ github.sha }}
        
        ## 功能特性
        - ✅ 用户登录验证（需要默认密码：12138）
        - ✅ 巡检任务自动化处理
        - ✅ 实时日志显示
        - ✅ 文件读写权限管理
        - ✅ 友好的移动端界面
        
        ## 安装说明
        1. 在Android设备上启用"未知来源"安装
        2. 下载APK文件到手机
        3. 点击APK文件进行安装
        4. 授予必要的文件读写权限
        
        ## 使用说明
        1. 打开应用，输入用户名和用户代码
        2. 输入默认密码：12138
        3. 登录后设置正确的数据目录路径
        4. 点击"开始巡检"按钮执行自动化任务
        
        ## 系统要求
        - Android 5.0 (API 21) 或更高版本
        - 至少50MB存储空间
        - 文件读写权限
        EOF
        
        tar -czf inspection-automation-release-${{ github.sha }}.tar.gz release/
        
    - name: Upload Release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: actions/upload-artifact@v3
      with:
        name: release-package
        path: |
          inspection-automation-release-*.tar.gz
          release/